openai_api_key = "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"

[admin]
username = "root"
password = "Lomtjjz"